//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoreoApp.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChoreoApp.i18n.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choreography Viewer.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ChoreographyAuthorPlaceholder {
            get {
                return ResourceManager.GetString("ChoreographyAuthorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ChoreographyCommentPlaceholder {
            get {
                return ResourceManager.GetString("ChoreographyCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ChoreographyDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ChoreographyDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string ChoreographyDisplayTitle {
            get {
                return ResourceManager.GetString("ChoreographyDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where from.
        /// </summary>
        public static string ChoreographyDrawPathFromLabel {
            get {
                return ResourceManager.GetString("ChoreographyDrawPathFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to.
        /// </summary>
        public static string ChoreographyDrawPathToLabel {
            get {
                return ResourceManager.GetString("ChoreographyDrawPathToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ChoreographyFloorBackLabel {
            get {
                return ResourceManager.GetString("ChoreographyFloorBackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor color.
        /// </summary>
        public static string ChoreographyFloorColorLabel {
            get {
                return ResourceManager.GetString("ChoreographyFloorColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string ChoreographyFloorFrontLabel {
            get {
                return ResourceManager.GetString("ChoreographyFloorFrontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string ChoreographyFloorLeftLabel {
            get {
                return ResourceManager.GetString("ChoreographyFloorLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string ChoreographyFloorRightLabel {
            get {
                return ResourceManager.GetString("ChoreographyFloorRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string ChoreographyFloorTitle {
            get {
                return ResourceManager.GetString("ChoreographyFloorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid lines.
        /// </summary>
        public static string ChoreographyGridLinesLabel {
            get {
                return ResourceManager.GetString("ChoreographyGridLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        public static string ChoreographyGridSizeLabel {
            get {
                return ResourceManager.GetString("ChoreographyGridSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ChoreographyNamePlaceholder {
            get {
                return ResourceManager.GetString("ChoreographyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions at side.
        /// </summary>
        public static string ChoreographyPositionsAtSideLabel {
            get {
                return ResourceManager.GetString("ChoreographyPositionsAtSideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choreography.
        /// </summary>
        public static string ChoreographySectionTitle {
            get {
                return ResourceManager.GetString("ChoreographySectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        public static string ChoreographyShowTimestampsLabel {
            get {
                return ResourceManager.GetString("ChoreographyShowTimestampsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string ChoreographySubtitlePlaceholder {
            get {
                return ResourceManager.GetString("ChoreographySubtitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string ChoreographyTransparencyLabel {
            get {
                return ResourceManager.GetString("ChoreographyTransparencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        public static string ChoreographyVariationPlaceholder {
            get {
                return ResourceManager.GetString("ChoreographyVariationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string DarkModeLabel {
            get {
                return ResourceManager.GetString("DarkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this scene.
        /// </summary>
        public static string DeleteSceneDialogDefaultName {
            get {
                return ResourceManager.GetString("DeleteSceneDialogDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scene &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteSceneDialogMessage {
            get {
                return ResourceManager.GetString("DeleteSceneDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DeleteSceneDialogNo {
            get {
                return ResourceManager.GetString("DeleteSceneDialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scene.
        /// </summary>
        public static string DeleteSceneDialogTitle {
            get {
                return ResourceManager.GetString("DeleteSceneDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DeleteSceneDialogYes {
            get {
                return ResourceManager.GetString("DeleteSceneDialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of sight.
        /// </summary>
        public static string ModeLineOfSight {
            get {
                return ResourceManager.GetString("ModeLineOfSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string ModeMove {
            get {
                return ResourceManager.GetString("ModeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate around center.
        /// </summary>
        public static string ModeRotateAroundCenter {
            get {
                return ResourceManager.GetString("ModeRotateAroundCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate around dancer.
        /// </summary>
        public static string ModeRotateAroundDancer {
            get {
                return ResourceManager.GetString("ModeRotateAroundDancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string ModeScale {
            get {
                return ResourceManager.GetString("ModeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ModeView {
            get {
                return ResourceManager.GetString("ModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SceneColorLabel {
            get {
                return ResourceManager.GetString("SceneColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed positions.
        /// </summary>
        public static string SceneFixedPositionsLabel {
            get {
                return ResourceManager.GetString("SceneFixedPositionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SceneNameLabel {
            get {
                return ResourceManager.GetString("SceneNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string SceneSectionTitle {
            get {
                return ResourceManager.GetString("SceneSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SceneTextLabel {
            get {
                return ResourceManager.GetString("SceneTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string SceneTimestampLabel {
            get {
                return ResourceManager.GetString("SceneTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
