<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Riok.Mapperly" Version="4.3.1" />
    <PackageVersion Include="SkiaSharp.Views.Maui.Core" Version="3.119.1" />
    <PackageVersion Include="StronglyTypedId" Version="1.0.0-beta08" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="MessagePipe" Version="1.8.1" />
  </ItemGroup>
  <ItemGroup Label="MAUI">
    <PackageVersion Include="Microsoft.Maui.Controls.Core" Version="10.0.20" />
    <PackageVersion Include="Microsoft.Maui.Graphics" Version="10.0.20" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.20" />
    <PackageVersion Include="Microsoft.Maui.Essentials" Version="10.0.20" />
    <PackageVersion Include="Microsoft.Maui.Controls.Foldable" Version="10.0.20" />
    <PackageVersion Include="Plugin.Maui.Audio" Version="4.0.0" />
    <PackageVersion Include="ThomasLevesque.WeakEvent" Version="4.1.0" />
    <PackageVersion Include="Sharpnado.Maui.Shadows" Version="2.0.2" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup Label="ReactiveUI">
    <PackageVersion Include="ReactiveUI" Version="22.3.1" />
    <PackageVersion Include="ReactiveUI.Maui" Version="22.3.1" />
    <PackageVersion Include="ReactiveUI.SourceGenerators" Version="2.5.1" />
    <PackageVersion Include="ReactiveUI.SourceGenerators.Analyzers.CodeFixes" Version="2.5.1" />
    <PackageVersion Include="DynamicData" Version="9.4.1" />
    <PackageVersion Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.3.1" />
  </ItemGroup>
  <ItemGroup Label="SkiaSharp">
    <PackageVersion Include="SkiaSharp" Version="3.119.1" />
    <PackageVersion Include="SkiaSharp.Views.Maui.Controls" Version="3.119.1" />
    <PackageVersion Include="SkiaSharp.Extended" Version="3.0.0" />
    <PackageVersion Include="Svg.Skia" Version="3.4.0" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Shouldly.FromAssert" Version="1.1.37" />
  </ItemGroup>
</Project>
