<Project>
    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ReactiveUI.SourceGenerators.Analyzers.CodeFixes">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="ReactiveUI" />
    <Using Include="ReactiveUI.SourceGenerators" />
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <FrameworkReference Update="Microsoft.NETCore.App" RuntimePackName="Microsoft.NETCore.App.Runtime.win-x64" />
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-arm64'">
    <FrameworkReference Update="Microsoft.NETCore.App" RuntimePackName="Microsoft.NETCore.App.Runtime.win-arm64" />
  </ItemGroup>
</Project>
