namespace MaterialDesignThemes.Maui;

public static class DataGridAssist
{
    private static readonly Thickness DefaultCellPaddingThickness = new(16, 8, 16, 8);
    private static readonly Thickness DefaultColumnHeaderPadding = new(16, 10, 16, 10);
    private static readonly CornerRadius DefaultCornerRadius = new(4);

    public static readonly BindableProperty AutoGeneratedCheckBoxStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedCheckBoxStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedCheckBoxStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedCheckBoxStyleProperty);

    public static void SetAutoGeneratedCheckBoxStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedCheckBoxStyleProperty, value);

    public static readonly BindableProperty AutoGeneratedEditingCheckBoxStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedEditingCheckBoxStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedEditingCheckBoxStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedEditingCheckBoxStyleProperty);

    public static void SetAutoGeneratedEditingCheckBoxStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedEditingCheckBoxStyleProperty, value);

    public static readonly BindableProperty AutoGeneratedTextStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedTextStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedTextStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedTextStyleProperty);

    public static void SetAutoGeneratedTextStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedTextStyleProperty, value);

    public static readonly BindableProperty AutoGeneratedEditingTextStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedEditingTextStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedEditingTextStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedEditingTextStyleProperty);

    public static void SetAutoGeneratedEditingTextStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedEditingTextStyleProperty, value);

    public static readonly BindableProperty AutoGeneratedComboBoxStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedComboBoxStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedComboBoxStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedComboBoxStyleProperty);

    public static void SetAutoGeneratedComboBoxStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedComboBoxStyleProperty, value);

    public static readonly BindableProperty AutoGeneratedEditingComboBoxStyleProperty =
        BindableProperty.CreateAttached(
            "AutoGeneratedEditingComboBoxStyle",
            typeof(Style),
            typeof(DataGridAssist),
            null);

    public static Style? GetAutoGeneratedEditingComboBoxStyle(BindableObject element) =>
        (Style?)element.GetValue(AutoGeneratedEditingComboBoxStyleProperty);

    public static void SetAutoGeneratedEditingComboBoxStyle(BindableObject element, Style? value) =>
        element.SetValue(AutoGeneratedEditingComboBoxStyleProperty, value);

    public static readonly BindableProperty ApplyMaterialDesignColumnStylesProperty =
        BindableProperty.CreateAttached(
            "ApplyMaterialDesignColumnStyles",
            typeof(bool),
            typeof(DataGridAssist),
            false);

    public static bool GetApplyMaterialDesignColumnStyles(BindableObject element) =>
        (bool)element.GetValue(ApplyMaterialDesignColumnStylesProperty);

    public static void SetApplyMaterialDesignColumnStyles(BindableObject element, bool value) =>
        element.SetValue(ApplyMaterialDesignColumnStylesProperty, value);

    public static readonly BindableProperty CellPaddingProperty =
        BindableProperty.CreateAttached(
            "CellPadding",
            typeof(Thickness),
            typeof(DataGridAssist),
            DefaultCellPaddingThickness);

    public static Thickness GetCellPadding(BindableObject element) =>
        (Thickness)element.GetValue(CellPaddingProperty);

    public static void SetCellPadding(BindableObject element, Thickness value) =>
        element.SetValue(CellPaddingProperty, value);

    public static readonly BindableProperty SelectedCellBorderBrushProperty =
        BindableProperty.CreateAttached(
            "SelectedCellBorderBrush",
            typeof(Brush),
            typeof(DataGridAssist),
            null);

    public static Brush? GetSelectedCellBorderBrush(BindableObject element) =>
        (Brush?)element.GetValue(SelectedCellBorderBrushProperty);

    public static void SetSelectedCellBorderBrush(BindableObject element, Brush? value) =>
        element.SetValue(SelectedCellBorderBrushProperty, value);

    public static readonly BindableProperty ColumnHeaderPaddingProperty =
        BindableProperty.CreateAttached(
            "ColumnHeaderPadding",
            typeof(Thickness),
            typeof(DataGridAssist),
            DefaultColumnHeaderPadding);

    public static Thickness GetColumnHeaderPadding(BindableObject element) =>
        (Thickness)element.GetValue(ColumnHeaderPaddingProperty);

    public static void SetColumnHeaderPadding(BindableObject element, Thickness value) =>
        element.SetValue(ColumnHeaderPaddingProperty, value);

    public static readonly BindableProperty EnableEditBoxAssistProperty =
        BindableProperty.CreateAttached(
            "EnableEditBoxAssist",
            typeof(bool),
            typeof(DataGridAssist),
            false);

    public static bool GetEnableEditBoxAssist(BindableObject element) =>
        (bool)element.GetValue(EnableEditBoxAssistProperty);

    public static void SetEnableEditBoxAssist(BindableObject element, bool value) =>
        element.SetValue(EnableEditBoxAssistProperty, value);

    public static readonly BindableProperty CornerRadiusProperty =
        BindableProperty.CreateAttached(
            "CornerRadius",
            typeof(CornerRadius),
            typeof(DataGridAssist),
            DefaultCornerRadius);

    public static CornerRadius GetCornerRadius(BindableObject element) =>
        (CornerRadius)element.GetValue(CornerRadiusProperty);

    public static void SetCornerRadius(BindableObject element, CornerRadius value) =>
        element.SetValue(CornerRadiusProperty, value);
}
