<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>
      net10.0;
      net10.0-android;
      net10.0-ios;
      net10.0-maccatalyst;
      net10.0-windows10.0.19041.0
    </TargetFrameworks>
    <OutputType>Library</OutputType>
    <UseMaui>true</UseMaui>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Microsoft.Maui" />
    <Using Include="Microsoft.Maui.Controls" />
    <Using Include="Microsoft.Maui.Graphics" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls.Core" />
    <PackageReference Include="PolySharp" />
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" />
    <PackageReference Include="Sharpnado.Maui.Shadows" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaterialColorUtilities\MaterialColorUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MaterialDesignColorsDictionary.*.cs">
      <DependentUpon>MaterialDesignColorsDictionary.cs</DependentUpon>
    </Compile>
    <Compile Update="TextBlockAssist.*.cs">
      <DependentUpon>TextBlockAssist.cs</DependentUpon>
    </Compile>
    <Compile Update="DrawerHost.*.cs">
      <DependentUpon>DrawerHost.cs</DependentUpon>
    </Compile>
    <Compile Update="ContentButton.IBorderElement.cs">
      <DependentUpon>ContentButton.cs</DependentUpon>
    </Compile>
    <Compile Update="TextFieldAssist.Windows.cs">
      <DependentUpon>TextFieldAssist.cs</DependentUpon>
    </Compile>
    <Compile Update="HintProxyFabric.*.cs">
      <DependentUpon>HintProxyFabric.cs</DependentUpon>
    </Compile>
    <Compile Update="Expander.Windows.cs">
      <DependentUpon>Expander.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <BundleResource Remove="Resources\Noto\OFL.txt" />
    <None Include="Resources\Noto\OFL.txt" />
  </ItemGroup>
  <ItemGroup>
    <MauiFont Include="Resources\**\*.ttf" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
    <Page Remove="Themes\**\*.xaml" />
    <ApplicationDefinition Remove="Themes\**\*.xaml" />
  </ItemGroup>
</Project>
