<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseMaui>true</UseMaui>
    <EnableMauiResizetizer>false</EnableMauiResizetizer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChoreoApp\ChoreoApp.csproj"
                      TargetFramework="net10.0-windows10.0.19041.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LightBDD.Framework" />
    <PackageReference Include="LightBDD.XUnit2" />
    <PackageReference Include="LightBDD.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Floor\MovePositions_feature.*.cs">
      <DependentUpon>MovePositions_feature.cs</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
